const CONTACT_TYPES = {
  ADD_CONTACT: "ADD_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  SET_CURRENT: "SET_CURRENT",
  CLEAR_CURRENT: "CLEAR_CURRENT",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  FILTER_CONTACT: "FILTER_CONTACT",
  CLEAR_FILTER: "CLEAR_FILTER",
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT"
};

export const {
  ADD_CONTACT,
  DELETE_CONTACT,
  SET_CURRENT,
  CLEAR_CURRENT,
  UPDATE_CONTACT,
  FILTER_CONTACT,
  CLEAR_FILTER,
  SET_ALERT,
  REMOVE_ALERT
} = CONTACT_TYPES;
